entity: wandb-apac
max_jobs: 2
queues:
  Initial Launch Queue
environment:
  type: aws
  region: us-east-2
repository:
  type: ecr
  name: s3://support-bucket-launch/launch/
builder:
  type: docker
  platform: linux/amd64