job: mohammadbakir/diabetes-prediction/xgb-classifier-diabetes:latest
metric:
  goal: maximize
  name: validation_0-custom_recall_score
run_cap: 4
scheduler:
  job: mohammadbakir/diabetes-prediction/optuna-scheduler:latest
  num_workers: 2
  settings:
    optuna_source: mohammadbakir/diabetes-prediction/optuna-config-diabetes-prediction:latest
    optuna_source_filename: optuna_diabetes_prediction.py
